language: node_js
cache:
    directories:
        - node_modules
notifications:
    email: false
node_js:
    - node
install:
    - yarn install
script:
    - npm run lint
after_success:
    - npm run semantic-release
